# Generated by Django 2.1 on 2022-06-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20220623_1427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
    ]
